export const TRANSFER_STATUS = {
    OTP_PENDING: 1,
    OTP_OVERTIME: 2,
    OTP_MAX_ATTEMPTS: 3,
    REJECTED_BY_TARGET_BANK: 4,
    CANCELED_BY_SENDER: 5,
    COMFIRMED: 6,
};

export default TRANSFER_STATUS;
