export const TRANSACTION_TYPES = {
    INTRABANK_TRANSFER: 1,
    INTRABANK_RECEIVE: 2,
    INTRABANK_TRANSFER_FEE: 3,
    INTERBANK_TRANSFER: 4,
    INTERBANK_RECEIVE: 5,
    INTERBANK_TRANSFER_FEE: 6,
    DEPOSIT: 7,
    PAY_DEBT_TRANSFER: 8,
    PAY_DEBT_RECEIVE: 9,
    CLOSE_ACCOUNT_TRANSFER: 10,
    CLOSE_ACCOUNT_RECEIVE: 11
};

export default TRANSACTION_TYPES;
