export const TRANSACTION_TYPES = {
    INTRABANK_TRANSFER: 1,
    INTRABANK_RECEIVE: 2,
    INTRABANK_TRANSFER_FEE: 3,
    INTERBANK_TRANSFER: 4,
    INTERBANK_RECEIVE: 5,
    INTERBANK_TRANSFER_FEE: 6,
    DEPOSITE: 7
};

export default TRANSACTION_TYPES;
